name: Deploy Jekyll Site to VPS

on:
  push:
    branches:
      - main  # O la rama que estés utilizando

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site
        run: bundle exec jekyll build

      - name: Upload site files
        uses: actions/upload-artifact@v2
        with:
          name: site-files
          path: _site  
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download site files
        uses: actions/download-artifact@v4
        with:
          name: site-files

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /opt/websites/mariotepro
            rm -rf *
            cp -r _site/* .
