name: Deploy Jekyll Site to VPS

on:
  push:
    branches:
      - main  # O la rama que estés utilizando

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site
        run: |
          bundle exec jekyll build
      
      - name: Copy to VPS via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          target: /opt/websites/mariotepro
          source: "_site/*"
