name: Deploy Jekyll Site to VPS

on:
  push:
    branches:
      - main  # O la rama que estés utilizando

jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          RUNNER_TOOL_CACHE: ${{ secrets.VPS_HOSTEDTOOLCACHE_PATH }}
        with:
          ruby-version: '3.0'  

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site
        run: |
          bundle exec jekyll build
      
      - name: Copy to VPS via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          target: ${{ secrets.VPS_DEPLOY_PATH }}
          source: "_site/*"
          strip_components: 1
          rm: true

      - name: Restart Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: sudo docker restart nginx
